version: 0.1.x.{build}
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
- SET
- 'echo System architecture: %PLATFORM%'
- 'echo %APPVEYOR_REPO_NAME%'

environment:
  winrm_user: winrm_test_user
  winrm_password: WinRM_test_Pass@w0rd1
  user_cert: c:\projects\ansible-win-ad-monitor\user.pem
  user_key: c:\projects\ansible-win-ad-monitor\key.pem
  user_pfx: c:\projects\ansible-win-ad-monitor\user.pfx
  CYGWIN: winsymlinks:nativestrict

  matrix:
  - TARGET: cygwin64
    CYG_ROOT: C:\cygwin64
    CYG_SETUP: C:\cygwin64\setup-x86_64.exe
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_BASH: C:\cygwin64\bin\sh
    ANSIBLE_VERSION: 2.5.11.0
    ANSIBLE_EXTRA_VARS:
  - TARGET: cygwin64
    CYG_ROOT: C:\cygwin64
    CYG_SETUP: C:\cygwin64\setup-x86_64.exe
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_BASH: C:\cygwin64\bin\sh
    ANSIBLE_VERSION: 2.6.7.0
    ANSIBLE_EXTRA_VARS:
  - TARGET: cygwin64
    CYG_ROOT: C:\cygwin64
    CYG_SETUP: C:\cygwin64\setup-x86_64.exe
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_BASH: C:\cygwin64\bin\sh
    ANSIBLE_VERSION: 2.7.1
    ANSIBLE_EXTRA_VARS:
matrix:
  fast_finish: true

install:
# setup winrm
- ps: net user /Y /add $env:winrm_user $env:winrm_password
- ps: net localgroup administrators $env:winrm_user /add
- ps: $env:PATH="C:\OpenSSL-Win64\bin;$env:PATH"
- ps: Import-Module $env:APPVEYOR_BUILD_FOLDER\test\appveyor\WinrmAppveyor.psm1
- ps: New-ClientCertificate $env:winrm_user $env:APPVEYOR_BUILD_FOLDER
- ps: $env:user_cert_thumb = (Import-pfxCertificate -FilePath $env:user_pfx -CertStoreLocation Cert:\LocalMachine\root).Thumbprint
- ps: Import-pfxCertificate -FilePath $env:user_pfx -CertStoreLocation Cert:\LocalMachine\TrustedPeople
- ps: $env:winrm_cert = (New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\localmachine\my).Thumbprint
- ps: winrm create winrm/config/Listener?Address=*+Transport=HTTPS "@{Hostname=`"localhost`";CertificateThumbprint=`"$($env:winrm_cert)`"}"
- ps: winrm set winrm/config/client/auth '@{Basic="true"}'
- ps: winrm set winrm/config/service/auth '@{Basic="true"}'
- ps: winrm set winrm/config/service/auth '@{Certificate="true"}'
- ps: winrm set winrm/config/service/auth '@{CbtHardeningLevel="Strict"}'
- ps: winrm set winrm/config/service '@{AllowUnencrypted="true"}'
- ps: New-WinrmUserCertificateMapping $env:user_cert_thumb
- ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
- ps: Write-Host $env:PATH
- ps: ($pwd).path
# setup ansible
- cmd: "%CYG_SETUP% -qgnNdO -l %CYG_CACHE% -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -P openssl-devel -P python2-devel -P python3-devel -P curl -P python-jinja -P python-crypto -P python-openssl -P python-setuptools -P git -P libffi-devel"
- cmd: "%CYG_BASH% -lc 'uname -a'"
- cmd: "%CYG_BASH% -lc 'python -m ensurepip'"
- cmd: "%CYG_BASH% -lc 'python3 -m ensurepip'"
- cmd: "%CYG_BASH% -lc 'python3 -m pip install --upgrade pip'"
- cmd: "%CYG_BASH% -lc 'python3 -m pip install pywinrm'"
- cmd: "%CYG_BASH% -lc 'python3 -m pip install ansible==%ANSIBLE_VERSION%'"
- cmd: "%CYG_BASH% -lc 'ansible --version'"
- cmd: "%CYG_BASH% -lc 'echo localhost ansible_user=$winrm_user ansible_password=$winrm_password ansible_connection=winrm'"
- cmd: "%CYG_BASH% -lc 'ls /'"
- cmd: "%CYG_BASH% -lc 'ls -l /cygdrive/c/'"
- cmd: "%CYG_BASH% -lc 'ls -l /cygdrive/c/projects/ansible-win-ad-monitor'"
- cmd: "%CYG_BASH% -lc pwd"
- cmd: "%CYG_BASH% -lc 'ansible -i /cygdrive/c/projects/ansible-win-ad-monitor/test/appveyor/inventory -m win_ping -vvv localhost'"
- cmd: "%CYG_BASH% -lc 'mkdir -p /etc/ansible/roles'"
- cmd: "%CYG_BASH% -lc 'cp -R /cygdrive/c/projects/ansible-win-ad-monitor /etc/ansible/roles/juju4.win-ad-monitor'"

build: off
test_script:
- cmd: "%CYG_BASH% -lc 'ansible-playbook /cygdrive/c/projects/ansible-win-ad-monitor/test/integration/default/default.yml --syntax-check'"
- cmd: "%CYG_BASH% -lc 'ansible-playbook -i /cygdrive/c/projects/ansible-win-ad-monitor/test/appveyor/inventory /cygdrive/c/projects/ansible-win-ad-monitor/test/integration/default/default.yml -vvv $ANSIBLE_EXTRA_VARS'"

after_test:
- cmd: |
    %CYG_BASH% -lc 'ansible-playbook -i /cygdrive/c/projects/ansible-win-ad-monitor/test/appveyor/inventory /cygdrive/c/projects/ansible-win-ad-monitor/test/integration/default/default.yml $ANSIBLE_EXTRA_VARS'
- ps: Get-ScheduledTask -TaskName "*monitor*"

on_failure:
- ps: Get-Content -Path "C:\ProgramData\Chocolatey\logs\chocolatey.log"

notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
