---

- name: Ensure ansible directories exist
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ win_temp_dir }}"
    - "{{ win_log_dir }}"

- name: Import monitor-AD
  ansible.builtin.import_tasks: monitor-AD.yml
- name: Import monitor-dcsyncmonitor
  ansible.builtin.import_tasks: monitor-dcsyncmonitor.yml
