---

- name: Ensure user _monitorsec is present
  win_user:
    name: "{{ win_admonitor_monitorsec_user }}"
    password: "{{ win_admonitor_monitorsec_password }}"
    state: present
    groups:
      - Users
  ignore_errors: true

# FIXME! user must have 'Log on as a batch job' right
# Computer Configuration\Windows Settings\Security Settings\Local Policies\User Rights Assignment
# if know SID beforehand, can be through secedit. else needs win2k3 support kit
- name: Ensure requirements are present
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items:
    - inspec
  ignore_errors: true

- name: add account to Log on as a service
  win_user_right:
    name: SeBatchLogonRight
    users:
    - "{{ win_admonitor_monitorsec_user }}"
    action: add

# No checksums options
- name: Monitor | download tools
  win_get_url:
    url: "{{ item.u }}"
    dest: "{{ win_temp_dir }}\\{{ item.f | default(item.u | basename) }}"
  with_items: "{{ win_monitorsec_tools }}"

- name: Monitor | unarchive tools
  win_unzip:
    src: "{{ win_temp_dir }}\\{{ item.f | default(item.u | basename) }}"
    dest: "{{ win_temp_dir }}\\{{ item.d }}"
    creates: "{{ win_temp_dir }}\\{{ item.d }}\\{{ item.creates }}"
  with_items: "{{ win_monitorsec_tools }}"

- name: Monitor daily run | Inspec windows-baseline
  win_command: "c:\\opscode\\inspec\\bin\\inspec.bat exec https://github.com/juju4/windows-baseline >{{ win_log_dir }}\\inspec.log"
  args:
    creates: "{{ win_log_dir }}\\inspec.log"
  ignore_errors: true

- name: Monitor daily run | Inspec
  win_scheduled_task:
    name: Daily-Security-Monitoring-Inspec
    description: Win state check
    executable: "c:\\opscode\\inspec\\bin\\inspec.bat"
    arguments: "exec https://github.com/juju4/windows-baseline --format=json >{{ win_log_dir }}\\inspec.log"
    time: 6am
    frequency: daily
    state: present
    enabled: yes
    user: "{{ win_schedtask_user }}"
    password: "{{ win_admonitor_monitorsec_password }}"
#    runlevel: highest

- name: Monitor daily run | PingCastle
  win_scheduled_task:
    name: Daily-Security-Monitoring-PingCastle
    description: AD state check
    executable: "{{ win_temp_dir }}\\PingCastle\\PingCastle.exe"
    arguments: "--healthcheck --server \"{{ win_domain }}\" --log"
    time: 6am
    frequency: daily
    state: present
    enabled: yes
    user: "{{ win_schedtask_user }}"
    password: "{{ win_admonitor_monitorsec_password }}"
#    runlevel: highest

- name: Monitor daily run | BloodHound-Sharphound
  win_scheduled_task:
    name: Daily-Security-Monitoring-Sharphound
    description: AD state check
    executable: "{{ win_temp_dir }}\\Bloodhound\\resources\\apps\\ingestors\\SharpHound.exe"
    time: 6am
    frequency: daily
    state: present
    enabled: yes
    user: "{{ win_schedtask_user }}"
    password: "{{ win_admonitor_monitorsec_password }}"
#    runlevel: highest

# https://github.com/l0ss/Grouper
- name: Monitor daily run | Get-GPOReport
  win_scheduled_task:
    name: Daily-Security-Monitoring-Get-GPOReport
    description: AD state check
    executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    arguments: "-ExecutionPolicy Unrestricted -NonInteractive -Command 'Get-GPOReport -All -ReportType xml -Path {{ win_temp_dir }}\\gporeport.xml'"
    time: 4am
    frequency: daily
    state: present
    enabled: yes
    user: "{{ win_schedtask_user }}"
    password: "{{ win_admonitor_monitorsec_password }}"
#    runlevel: highest
